title: "Thiago Orbite Barreto"
description: "Site pessoal convertido para Jekyll"
url: "https://thiago-orbite-barreto.github.io"
baseurl: "/site-pessoal"
markdown: kramdown
permalink: /:year/:month/:day/:title/
#theme: minima
